const HittingStats = [
    {
        "#": "5",
        "Player": "Cole McConnell",
        "AVG": ".378",
        "GP-GS": "60-60",
        "AB": "249",
        "R": "67",
        "H": "94",
        "2B": "17",
        "3B": "1",
        "HR": "18",
        "RBI": "71",
        "TB": "167",
        "SLG%": ".671",
        "BB": "29",
        "HBP": "13",
        "SO": "71",
        "GDP": "2",
        "OB%": ".461",
        "SF": "4",
        "SH": "0",
        "SB-ATT": "1-2",
        "PO": "103",
        "A": "1",
        "E": "1",
        "FLD%": ".990"
    },
    {
        "#": "16",
        "Player": "Ethan Bates",
        "AVG": ".337",
        "GP-GS": "64-64",
        "AB": "258",
        "R": "68",
        "H": "87",
        "2B": "21",
        "3B": "2",
        "HR": "15",
        "RBI": "74",
        "TB": "157",
        "SLG%": ".609",
        "BB": "37",
        "HBP": "13",
        "SO": "22",
        "GDP": "0",
        "OB%": ".436",
        "SF": "6",
        "SH": "1",
        "SB-ATT": "2-2",
        "PO": "6",
        "A": "9",
        "E": "1",
        "FLD%": ".938"
    },
    {
        "#": "24",
        "Player": "Dalton Davis",
        "AVG": ".324",
        "GP-GS": "54-54",
        "AB": "222",
        "R": "57",
        "H": "72",
        "2B": "11",
        "3B": "1",
        "HR": "15",
        "RBI": "53",
        "TB": "130",
        "SLG%": ".586",
        "BB": "34",
        "HBP": "7",
        "SO": "21",
        "GDP": "1",
        "OB%": ".423",
        "SF": "4",
        "SH": "0",
        "SB-ATT": "8-8",
        "PO": "315",
        "A": "15",
        "E": "0",
        "FLD%": "1.000"
    },
    {
        "#": "12",
        "Player": "Jorge Corona",
        "AVG": ".316",
        "GP-GS": "58-57",
        "AB": "244",
        "R": "45",
        "H": "77",
        "2B": "14",
        "3B": "0",
        "HR": "16",
        "RBI": "51",
        "TB": "139",
        "SLG%": ".570",
        "BB": "26",
        "HBP": "4",
        "SO": "47",
        "GDP": "5",
        "OB%": ".388",
        "SF": "2",
        "SH": "0",
        "SB-ATT": "0-0",
        "PO": "540",
        "A": "59",
        "E": "3",
        "FLD%": ".995"
    },
    {
        "#": "7",
        "Player": "Michael Ballard",
        "AVG": ".312",
        "GP-GS": "64-64",
        "AB": "247",
        "R": "33",
        "H": "77",
        "2B": "12",
        "3B": "0",
        "HR": "4",
        "RBI": "38",
        "TB": "101",
        "SLG%": ".409",
        "BB": "31",
        "HBP": "3",
        "SO": "42",
        "GDP": "5",
        "OB%": ".392",
        "SF": "2",
        "SH": "4",
        "SB-ATT": "2-3",
        "PO": "121",
        "A": "178",
        "E": "1",
        "FLD%": ".997"
    },
    {
        "#": "6",
        "Player": "Adarius Myers",
        "AVG": ".297",
        "GP-GS": "64-64",
        "AB": "259",
        "R": "35",
        "H": "77",
        "2B": "19",
        "3B": "0",
        "HR": "3",
        "RBI": "35",
        "TB": "105",
        "SLG%": ".405",
        "BB": "28",
        "HBP": "5",
        "SO": "43",
        "GDP": "3",
        "OB%": ".372",
        "SF": "4",
        "SH": "2",
        "SB-ATT": "8-13",
        "PO": "108",
        "A": "0",
        "E": "1",
        "FLD%": ".991"
    },
    {
        "#": "18",
        "Player": "Kasten Furr",
        "AVG": ".271",
        "GP-GS": "64-64",
        "AB": "236",
        "R": "70",
        "H": "64",
        "2B": "7",
        "3B": "2",
        "HR": "5",
        "RBI": "28",
        "TB": "90",
        "SLG%": ".381",
        "BB": "34",
        "HBP": "23",
        "SO": "42",
        "GDP": "2",
        "OB%": ".409",
        "SF": "3",
        "SH": "4",
        "SB-ATT": "4-4",
        "PO": "80",
        "A": "177",
        "E": "15",
        "FLD%": ".945"
    },
    {
        "#": "14",
        "Player": "Grant Comeaux",
        "AVG": ".261",
        "GP-GS": "55-50",
        "AB": "199",
        "R": "28",
        "H": "52",
        "2B": "7",
        "3B": "0",
        "HR": "3",
        "RBI": "28",
        "TB": "68",
        "SLG%": ".342",
        "BB": "10",
        "HBP": "12",
        "SO": "53",
        "GDP": "3",
        "OB%": ".329",
        "SF": "4",
        "SH": "1",
        "SB-ATT": "0-2",
        "PO": "234",
        "A": "38",
        "E": "8",
        "FLD%": ".971"
    },
    {
        "#": "10",
        "Player": "Logan McLeod",
        "AVG": ".246",
        "GP-GS": "41-37",
        "AB": "118",
        "R": "22",
        "H": "29",
        "2B": "4",
        "3B": "1",
        "HR": "1",
        "RBI": "14",
        "TB": "38",
        "SLG%": ".322",
        "BB": "18",
        "HBP": "10",
        "SO": "30",
        "GDP": "1",
        "OB%": ".388",
        "SF": "1",
        "SH": "0",
        "SB-ATT": "1-2",
        "PO": "11",
        "A": "55",
        "E": "6",
        "FLD%": ".917"
    },
    {
        "#": "3",
        "Player": "Will Safford",
        "AVG": ".198",
        "GP-GS": "46-39",
        "AB": "131",
        "R": "24",
        "H": "26",
        "2B": "4",
        "3B": "0",
        "HR": "7",
        "RBI": "24",
        "TB": "51",
        "SLG%": ".389",
        "BB": "22",
        "HBP": "5",
        "SO": "37",
        "GDP": "4",
        "OB%": ".329",
        "SF": "3",
        "SH": "9",
        "SB-ATT": "3-4",
        "PO": "57",
        "A": "8",
        "E": "3",
        "FLD%": ".956"
    },
    {
        "#": "4",
        "Player": "Brody Drost",
        "AVG": ".186",
        "GP-GS": "17-11",
        "AB": "43",
        "R": "7",
        "H": "8",
        "2B": "1",
        "3B": "0",
        "HR": "1",
        "RBI": "4",
        "TB": "12",
        "SLG%": ".279",
        "BB": "7",
        "HBP": "2",
        "SO": "17",
        "GDP": "0",
        "OB%": ".327",
        "SF": "0",
        "SH": "0",
        "SB-ATT": "0-0",
        "PO": "29",
        "A": "0",
        "E": "1",
        "FLD%": ".967"
    },
    {
        "#": "44",
        "Player": "Karson Evans",
        "AVG": ".176",
        "GP-GS": "14-9",
        "AB": "34",
        "R": "5",
        "H": "6",
        "2B": "1",
        "3B": "0",
        "HR": "1",
        "RBI": "4",
        "TB": "10",
        "SLG%": ".294",
        "BB": "6",
        "HBP": "1",
        "SO": "4",
        "GDP": "2",
        "OB%": ".317",
        "SF": "0",
        "SH": "0",
        "SB-ATT": "0-0",
        "PO": "79",
        "A": "2",
        "E": "0",
        "FLD%": "1.000"
    },
    {
        "#": "2",
        "Player": "Thaxton Berch",
        "AVG": ".091",
        "GP-GS": "13-3",
        "AB": "11",
        "R": "4",
        "H": "1",
        "2B": "0",
        "3B": "0",
        "HR": "0",
        "RBI": "1",
        "TB": "1",
        "SLG%": ".091",
        "BB": "1",
        "HBP": "0",
        "SO": "4",
        "GDP": "0",
        "OB%": ".167",
        "SF": "0",
        "SH": "1",
        "SB-ATT": "1-1",
        "PO": "4",
        "A": "0",
        "E": "0",
        "FLD%": "1.000"
    },
    {
        "#": "17",
        "Player": "Slade Netterville",
        "AVG": ".000",
        "GP-GS": "6-0",
        "AB": "5",
        "R": "0",
        "H": "0",
        "2B": "0",
        "3B": "0",
        "HR": "0",
        "RBI": "0",
        "TB": "0",
        "SLG%": ".000",
        "BB": "0",
        "HBP": "0",
        "SO": "2",
        "GDP": "0",
        "OB%": ".000",
        "SF": "0",
        "SH": "0",
        "SB-ATT": "0-0",
        "PO": "1",
        "A": "2",
        "E": "0",
        "FLD%": "1.000"
    },
    {
        "#": "9",
        "Player": "Colton Coates",
        "AVG": ".000",
        "GP-GS": "5-0",
        "AB": "4",
        "R": "0",
        "H": "0",
        "2B": "0",
        "3B": "0",
        "HR": "0",
        "RBI": "0",
        "TB": "0",
        "SLG%": ".000",
        "BB": "1",
        "HBP": "0",
        "SO": "2",
        "GDP": "0",
        "OB%": ".200",
        "SF": "0",
        "SH": "0",
        "SB-ATT": "0-0",
        "PO": "1",
        "A": "0",
        "E": "0",
        "FLD%": "1.000"
    }
];

const PitchingStats = [
    {
        "#": "31",
        "Player": "Sam Brodersen",
        "ERA": "3.05",
        "W-L": "8-1",
        "APP": "33",
        "GS": "0",
        "CG": "0",
        "SHO": "0-2",
        "SV": "1",
        "IP": "56.0",
        "H": "31",
        "R": "21",
        "ER": "19",
        "BB": "40",
        "SO": "96",
        "2B": "5",
        "3B": "2",
        "HR": "5",
        "B/AVG": ".160",
        "WP": "2",
        "HP": "4",
        "BK": "2",
        "SFA": "0",
        "SHA": "2"
    },
    {
        "#": "16",
        "Player": "Ethan Bates",
        "ERA": "3.43",
        "W-L": "2-1",
        "APP": "36",
        "GS": "0",
        "CG": "0",
        "SHO": "0-2",
        "SV": "17",
        "IP": "44.2",
        "H": "29",
        "R": "19",
        "ER": "17",
        "BB": "20",
        "SO": "52",
        "2B": "5",
        "3B": "1",
        "HR": "1",
        "B/AVG": ".180",
        "WP": "1",
        "HP": "9",
        "BK": "0",
        "SFA": "0",
        "SHA": "1"
    },
    {
        "#": "20",
        "Player": "Grant Hubka",
        "ERA": "4.08",
        "W-L": "4-0",
        "APP": "28",
        "GS": "5",
        "CG": "0",
        "SHO": "0-2",
        "SV": "1",
        "IP": "57.1",
        "H": "44",
        "R": "29",
        "ER": "26",
        "BB": "34",
        "SO": "68",
        "2B": "8",
        "3B": "2",
        "HR": "9",
        "B/AVG": ".215",
        "WP": "1",
        "HP": "6",
        "BK": "0",
        "SFA": "4",
        "SHA": "2"
    },
    {
        "#": "33",
        "Player": "Connor Nation",
        "ERA": "4.15",
        "W-L": "5-0",
        "APP": "23",
        "GS": "5",
        "CG": "0",
        "SHO": "0-0",
        "SV": "0",
        "IP": "39.0",
        "H": "44",
        "R": "23",
        "ER": "18",
        "BB": "12",
        "SO": "37",
        "2B": "3",
        "3B": "1",
        "HR": "7",
        "B/AVG": ".284",
        "WP": "2",
        "HP": "6",
        "BK": "0",
        "SFA": "0",
        "SHA": "2"
    },
    {
        "#": "32",
        "Player": "Luke Nichols",
        "ERA": "4.46",
        "W-L": "4-4",
        "APP": "17",
        "GS": "16",
        "CG": "1",
        "SHO": "0-1",
        "SV": "0",
        "IP": "78.2",
        "H": "74",
        "R": "47",
        "ER": "39",
        "BB": "29",
        "SO": "82",
        "2B": "9",
        "3B": "2",
        "HR": "7",
        "B/AVG": ".249",
        "WP": "7",
        "HP": "12",
        "BK": "0",
        "SFA": "3",
        "SHA": "5"
    },
    {
        "#": "52",
        "Player": "Brenton Thiels",
        "ERA": "4.50",
        "W-L": "0-0",
        "APP": "2",
        "GS": "0",
        "CG": "0",
        "SHO": "0-0",
        "SV": "0",
        "IP": "2.0",
        "H": "2",
        "R": "1",
        "ER": "1",
        "BB": "2",
        "SO": "2",
        "2B": "1",
        "3B": "0",
        "HR": "0",
        "B/AVG": ".250",
        "WP": "0",
        "HP": "0",
        "BK": "0",
        "SFA": "0",
        "SHA": "0"
    },
    {
        "#": "45",
        "Player": "Jacob Havern",
        "ERA": "4.61",
        "W-L": "3-3",
        "APP": "18",
        "GS": "2",
        "CG": "0",
        "SHO": "0-2",
        "SV": "0",
        "IP": "27.1",
        "H": "28",
        "R": "15",
        "ER": "14",
        "BB": "13",
        "SO": "28",
        "2B": "4",
        "3B": "0",
        "HR": "1",
        "B/AVG": ".264",
        "WP": "4",
        "HP": "6",
        "BK": "1",
        "SFA": "1",
        "SHA": "0"
    },
    {
        "#": "38",
        "Player": "Nate Crider",
        "ERA": "4.70",
        "W-L": "3-0",
        "APP": "15",
        "GS": "0",
        "CG": "0",
        "SHO": "0-0",
        "SV": "0",
        "IP": "15.1",
        "H": "13",
        "R": "8",
        "ER": "8",
        "BB": "8",
        "SO": "13",
        "2B": "4",
        "3B": "0",
        "HR": "3",
        "B/AVG": ".236",
        "WP": "1",
        "HP": "1",
        "BK": "0",
        "SFA": "1",
        "SHA": "0"
    },
    {
        "#": "26",
        "Player": "Blake Hooks",
        "ERA": "5.06",
        "W-L": "1-0",
        "APP": "25",
        "GS": "0",
        "CG": "0",
        "SHO": "0-1",
        "SV": "0",
        "IP": "32.0",
        "H": "33",
        "R": "21",
        "ER": "18",
        "BB": "17",
        "SO": "30",
        "2B": "11",
        "3B": "0",
        "HR": "0",
        "B/AVG": ".268",
        "WP": "4",
        "HP": "12",
        "BK": "0",
        "SFA": "1",
        "SHA": "2"
    },
    {
        "#": "36",
        "Player": "Greg Martinez",
        "ERA": "5.68",
        "W-L": "0-0",
        "APP": "10",
        "GS": "1",
        "CG": "0",
        "SHO": "0-0",
        "SV": "0",
        "IP": "19.0",
        "H": "19",
        "R": "13",
        "ER": "12",
        "BB": "11",
        "SO": "18",
        "2B": "2",
        "3B": "0",
        "HR": "4",
        "B/AVG": ".264",
        "WP": "5",
        "HP": "4",
        "BK": "0",
        "SFA": "0",
        "SHA": "0"
    },
    {
        "#": "40",
        "Player": "Reed Smith",
        "ERA": "5.99",
        "W-L": "7-5",
        "APP": "19",
        "GS": "17",
        "CG": "0",
        "SHO": "0-2",
        "SV": "0",
        "IP": "76.2",
        "H": "91",
        "R": "55",
        "ER": "51",
        "BB": "18",
        "SO": "78",
        "2B": "15",
        "3B": "3",
        "HR": "15",
        "B/AVG": ".290",
        "WP": "6",
        "HP": "8",
        "BK": "0",
        "SFA": "0",
        "SHA": "3"
    },
    {
        "#": "29",
        "Player": "Issac Crabb",
        "ERA": "6.48",
        "W-L": "0-0",
        "APP": "8",
        "GS": "0",
        "CG": "0",
        "SHO": "0-1",
        "SV": "0",
        "IP": "8.1",
        "H": "8",
        "R": "6",
        "ER": "6",
        "BB": "6",
        "SO": "8",
        "2B": "1",
        "3B": "1",
        "HR": "3",
        "B/AVG": ".258",
        "WP": "1",
        "HP": "3",
        "BK": "0",
        "SFA": "0",
        "SHA": "0"
    },
    {
        "#": "28",
        "Player": "Caden Copeland",
        "ERA": "7.58",
        "W-L": "3-2",
        "APP": "18",
        "GS": "5",
        "CG": "0",
        "SHO": "0-1",
        "SV": "0",
        "IP": "29.2",
        "H": "38",
        "R": "28",
        "ER": "25",
        "BB": "14",
        "SO": "31",
        "2B": "8",
        "3B": "0",
        "HR": "1",
        "B/AVG": ".311",
        "WP": "0",
        "HP": "11",
        "BK": "0",
        "SFA": "1",
        "SHA": "1"
    },
    {
        "#": "34",
        "Player": "Turner Swistak",
        "ERA": "7.98",
        "W-L": "5-3",
        "APP": "16",
        "GS": "13",
        "CG": "0",
        "SHO": "0-0",
        "SV": "1",
        "IP": "53.0",
        "H": "68",
        "R": "52",
        "ER": "47",
        "BB": "17",
        "SO": "53",
        "2B": "19",
        "3B": "2",
        "HR": "14",
        "B/AVG": ".315",
        "WP": "2",
        "HP": "5",
        "BK": "1",
        "SFA": "2",
        "SHA": "3"
    },
    {
        "#": "39",
        "Player": "Ryan Harland",
        "ERA": "8.65",
        "W-L": "0-0",
        "APP": "20",
        "GS": "0",
        "CG": "0",
        "SHO": "0-1",
        "SV": "0",
        "IP": "26.0",
        "H": "32",
        "R": "25",
        "ER": "25",
        "BB": "13",
        "SO": "22",
        "2B": "4",
        "3B": "1",
        "HR": "6",
        "B/AVG": ".299",
        "WP": "1",
        "HP": "1",
        "BK": "0",
        "SFA": "1",
        "SHA": "1"
    },
    {
        "#": "37",
        "Player": "Reece Tarini",
        "ERA": "9.00",
        "W-L": "0-0",
        "APP": "2",
        "GS": "0",
        "CG": "0",
        "SHO": "0-0",
        "SV": "0",
        "IP": "2.0",
        "H": "2",
        "R": "2",
        "ER": "2",
        "BB": "1",
        "SO": "1",
        "2B": "0",
        "3B": "0",
        "HR": "2",
        "B/AVG": ".286",
        "WP": "0",
        "HP": "0",
        "BK": "0",
        "SFA": "0",
        "SHA": "0"
    },
    {
        "#": "46",
        "Player": "Hayden Harmon",
        "ERA": "99.00",
        "W-L": "0-0",
        "APP": "1",
        "GS": "0",
        "CG": "0",
        "SHO": "0-0",
        "SV": "0",
        "IP": "0.0",
        "H": "0",
        "R": "2",
        "ER": "2",
        "BB": "2",
        "SO": "0",
        "2B": "0",
        "3B": "0",
        "HR": "0",
        "B/AVG": ".000",
        "WP": "1",
        "HP": "1",
        "BK": "0",
        "SFA": "0",
        "SHA": "0"
    }
]

const FieldingStats = [
    {
        "#": "24",
        "Player": "Dalton Davis",
        "C": "330",
        "PO": "315",
        "A": "1,5",
        "E": "0",
        "FLD%": "1.000",
        "DP": "26",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "44",
        "Player": "Karson Evans",
        "C": "81",
        "PO": "79",
        "A": "2",
        "E": "0",
        "FLD%": "1.000",
        "DP": "1",
        "SBA": "12",
        "CSB": "1",
        "SBA%": ".923",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "31",
        "Player": "Sam Brodersen",
        "C": "8",
        "PO": "2",
        "A": "6",
        "E": "0",
        "FLD%": "1.000",
        "DP": "0",
        "SBA": "3",
        "CSB": "2",
        "SBA%": ".600",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "45",
        "Player": "Jacob Havern",
        "C": " 6",
        "PO": "3",
        "A": "3",
        "E": "0",
        "FLD%": "1.000",
        "DP": "0",
        "SBA": "2",
        "CSB": "0",
        "SBA%": "1",
        "PB": ".000",
        "CI": "0"
    },
    {
        "#": "39",
        "Player": "Ryan Harland",
        "C": " 5",
        "PO": "0",
        "A": "5",
        "E": "0",
        "FLD%": "1.000",
        "DP": "0",
        "SBA": "2",
        "CSB": "1",
        "SBA%": ".667",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "2",
        "Player": "Thaxton Berch",
        "C": "4",
        "PO": "4",
        "A": "0",
        "E": "0",
        "FLD%": "1.000",
        "DP": "0",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "28",
        "Player": "Caden Copeland",
        "C": "4",
        "PO": "2",
        "A": "2",
        "E": "0",
        "FLD%": "1.000",
        "DP": "1",
        "SBA": "8",
        "CSB": "1",
        "SBA%": ".889",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "33",
        "Player": "Connor Nation",
        "C": "4",
        "PO": "0",
        "A": "4",
        "E": "0",
        "FLD%": "1.000",
        "DP": "0",
        "SBA": "4",
        "CSB": "2",
        "SBA%": ".667",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "17",
        "Player": "Slade Netterville",
        "C": "3",
        "PO": "1",
        "A": "2",
        "E": "0",
        "FLD%": "1.000",
        "DP": "0",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "38",
        "Player": "Nate Crider",
        "C": "3",
        "PO": "0",
        "A": "3",
        "E": "0",
        "FLD%": "1.000",
        "DP": "0",
        "SBA": "1",
        "CSB": "0",
        "SBA%": "1.000",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "29",
        "Player": "Isaac Crabb",
        "C": "1",
        "PO": "0",
        "A": "1",
        "E": "0",
        "FLD%": "1.000",
        "DP": "0",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "36",
        "Player": "Greg Martinez",
        "C": "1",
        "PO": "0",
        "A": "1",
        "E": "0",
        "FLD%": "1.000",
        "DP": "0",
        "SBA": "2",
        "CSB": "1",
        "SBA%": ".667",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "37",
        "Player": "Reece Tarini",
        "C": "1",
        "PO": "0",
        "A": "1",
        "E": "0",
        "FLD%": "1.000",
        "DP": "0",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "9",
        "Player": "Colton Coates",
        "C": "1",
        "PO": "1",
        "A": "0",
        "E": "0",
        "FLD%": "1.000",
        "DP": "0",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "7",
        "Player": "Michael Ballard",
        "C": "300",
        "PO": "121",
        "A": "178",
        "E": "1",
        "FLD%": ".997",
        "DP": "37",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "12",
        "Player": "Jorge Corona",
        "C": "602",
        "PO": "540",
        "A": "59",
        "E": "3",
        "FLD%": ".995",
        "DP": "1",
        "SBA": "52",
        "CSB": "24",
        "SBA%": ".684",
        "PB": "10",
        "CI": "0"
    },
    {
        "#": "6",
        "Player": "Adarius Myers",
        "C": "109",
        "PO": "108",
        "A": "0",
        "E": "1",
        "FLD%": ".991",
        "DP": "0",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "5",
        "Player": "Cole McConnell",
        "C": "105",
        "PO": "103",
        "A": "1",
        "E": "1",
        "FLD%": ".990",
        "DP": "0",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "14",
        "Player": "Grant Comeaux",
        "C": "280",
        "PO": "234",
        "A": "38",
        "E": "8",
        "FLD%": ".971",
        "DP": "1,9",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "4",
        "Player": "Brody Drost",
        "C": "30",
        "PO": "29",
        "A": "0",
        "E": "1",
        "FLD%": ".967",
        "DP": "0",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "3",
        "Player": "Will Safford",
        "C": "68",
        "PO": "57",
        "A": "8",
        "E": "3",
        "FLD%": ".956",
        "DP": "0",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "18",
        "Player": "Kasten Furr",
        "C": "272",
        "PO": "80",
        "A": "177",
        "E": "15",
        "FLD%": ".945",
        "DP": "33",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "16",
        "Player": "Ethan Bates",
        "C": "16",
        "PO": "6",
        "A": "9",
        "E": "1",
        "FLD%": ".938",
        "DP": "1",
        "SBA": "4",
        "CSB": "0",
        "SBA%": "1.000",
        "PB": " 0",
        "CI": "0"
    },
    {
        "#": "34",
        "Player": "Turner Swistak",
        "C": "13",
        "PO": "2",
        "A": "10",
        "E": "1",
        "FLD%": ".923",
        "DP": "0",
        "SBA": "5",
        "CSB": "5",
        "SBA%": ".500",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "10",
        "Player": "Logan McLeod",
        "C": "72",
        "PO": "11",
        "A": "55",
        "E": "6",
        "FLD%": ".917",
        "DP": "6",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "40",
        "Player": "Reed Smith",
        "C": "10",
        "PO": "0",
        "A": "9",
        "E": "1",
        "FLD%": ".900,0",
        "DP": "0",
        "SBA": "9",
        "CSB": "5",
        "SBA%": ".643",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "32",
        "Player": "Luke Nichols",
        "C": "15",
        "PO": "2",
        "A": "11",
        "E": "2",
        "FLD%": ".867",
        "DP": "0",
        "SBA": "8",
        "CSB": "2",
        "SBA%": ".800",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "26",
        "Player": "Blake Hooks ",
        "C": "7",
        "PO": "1",
        "A": "4",
        "E": "2",
        "FLD%": ".714",
        "DP": "0",
        "SBA": "7",
        "CSB": "0",
        "SBA%": "1.000",
        "PB": " 0",
        "CI": "0"
    },
    {
        "#": "20",
        "Player": "Grant Hubka",
        "C": "6",
        "PO": "0",
        "A": "4",
        "E": "2",
        "FLD%": ".667",
        "DP": "0",
        "SBA": "9",
        "CSB": "7",
        "SBA%": ".563",
        "PB": "0",
        "CI": "0"
    },
    {
        "#": "46",
        "Player": "Hayden Harmon",
        "C": "0",
        "PO": "0",
        "A": "0",
        "E": "0",
        "FLD%": ".000",
        "DP": "0",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0"
    },
    {
        "#": "52",
        "Player": "Brenton Thiels",
        "C": "0",
        "PO": "0",
        "A": "0",
        "E": "0",
        "FLD%": ".000",
        "DP": "0",
        "SBA": "0",
        "CSB": "0",
        "SBA%": "0",
        "PB": "0"
    }
]

const AdvBatting = [
    {
        "Number": "5",
        "Player": "Cole McConnell",
        "OPS": "1.132",
        "SO%": "28.51%",
        "BB%": "9.83%",
        "RC": "98.67",
        "ISO": "0.293",
        "BABIP": "0.373",
        "wOBA": "0.467"
    },
    {
        "Number": "16",
        "Player": "Ethan Bates",
        "OPS": "1.045",
        "SO%": "8.53%",
        "BB%": "11.75%",
        "RC": "82.48",
        "ISO": "0.272",
        "BABIP": "0.349",
        "wOBA": "0.426"
    },
    {
        "Number": "24",
        "Player": "Dalton Davis",
        "OPS": "1.009",
        "SO%": "9.46%",
        "BB%": "12.73%",
        "RC": "70.37",
        "ISO": "0.262",
        "BABIP": "0.322",
        "wOBA": "0.417"
    },
    {
        "Number": "12",
        "Player": "Jorge Corona",
        "OPS": "0.958",
        "SO%": "19.26%",
        "BB%": "9.42%",
        "RC": "63.90",
        "ISO": "0.254",
        "BABIP": "0.337",
        "wOBA": "0.388"
    },
    {
        "Number": "7",
        "Player": "Michael Ballard",
        "OPS": "0.801",
        "SO%": "17.00%",
        "BB%": "10.80%",
        "RC": "42.19",
        "ISO": "0.097",
        "BABIP": "0.318",
        "wOBA": "0.363"
    },
    {
        "Number": "6",
        "Player": "Adarius Myers",
        "OPS": "0.777",
        "SO%": "16.60%",
        "BB%": "10.81%",
        "RC": "42.05",
        "ISO": "0.108",
        "BABIP": "0.323",
        "wOBA": "0.344"
    },
    {
        "Number": "18",
        "Player": "Kasten Furr",
        "OPS": "0.790",
        "SO%": "17.80%",
        "BB%": "14.41%",
        "RC": "37.18",
        "ISO": "0.110",
        "BABIP": "0.278",
        "wOBA": "0.343"
    },
    {
        "Number": "14",
        "Player": "Grant Comeaux",
        "OPS": "0.671",
        "SO%": "26.63%",
        "BB%": "5.03%",
        "RC": "19.15",
        "ISO": "0.081",
        "BABIP": "0.292",
        "wOBA": "0.313"
    },
    {
        "Number": "10",
        "Player": "Logan McLeod",
        "OPS": "0.710",
        "SO%": "25.42%",
        "BB%": "14.29%",
        "RC": "15.20",
        "ISO": "0.076",
        "BABIP": "0.321",
        "wOBA": "0.332"
    },
    {
        "Number": "3",
        "Player": "Will Safford",
        "OPS": "0.718",
        "SO%": "28.24%",
        "BB%": "15.32%",
        "RC": "11.80",
        "ISO": "0.191",
        "BABIP": "0.226",
        "wOBA": "0.332"
    },
    {
        "Number": "4",
        "Player": "Brody Drost",
        "OPS": "0.606",
        "SO%": "39.53%",
        "BB%": "14.89%",
        "RC": "3.620",
        "ISO": "0.093",
        "BABIP": "0.276",
        "wOBA": "0.317"
    },
    {
        "Number": "44",
        "Player": "Karson Evans",
        "OPS": "0.611",
        "SO%": "11.76%",
        "BB%": "15.00%",
        "RC": "3.900",
        "ISO": "0.118",
        "BABIP": "0.286",
        "wOBA": "0.300"
    },
    {
        "Number": "2",
        "Player": "Thaxton Berch",
        "OPS": "0.258",
        "SO%": "36.36%",
        "BB%": "7.14%",
        "RC": "0.070",
        "ISO": "0.000",
        "BABIP": "0.100",
        "wOBA": "0.160"
    },
    {
        "Number": "17",
        "Player": "Slade Netterville",
        "OPS": "0.000",
        "SO%": "40.00%",
        "BB%": "0.00%",
        "RC": "0.000",
        "ISO": "0.000",
        "BABIP": "0.000",
        "wOBA": "0.000"
    },
    {
        "Number": "9",
        "Player": "Colton Coates",
        "OPS": "0.200",
        "SO%": "50.00%",
        "BB%": "20.00%",
        "RC": "0.000",
        "ISO": "0.000",
        "BABIP": "0.000",
        "wOBA": "0.000"
    }
]

const AdvPitching = [
    {
        "Number": "31",
        "Player": "Sam Brodersen",
        "FIP": "2.64",
        "WHIP": "1.27",
        "K%": "36.22",
        "BB%": "15.09",
        "LOB%": "72.72"
    },
    {
        "Number": "16",
        "Player": "Ethan Bates",
        "FIP": "2.77",
        "WHIP": "1.10",
        "K%": "28.00",
        "BB%": "10.99",
        "LOB%": "75.00"
    },
    {
        "Number": "20",
        "Player": "Grant Hubka",
        "FIP": "3.82",
        "WHIP": "1.37",
        "K%": "26.61",
        "BB%": "13.63",
        "LOB%": "75.22"
    },
    {
        "Number": "33",
        "Player": "Connor Nation",
        "FIP": "4.28",
        "WHIP": "1.44",
        "K%": "21.88",
        "BB%": "7.29",
        "LOB%": "77.27"
    },
    {
        "Number": "32",
        "Player": "Luke Nichols",
        "FIP": "4.28",
        "WHIP": "1.31",
        "K%": "21.16",
        "BB%": "7.78",
        "LOB%": "74.62"
    },
    {
        "Number": "52",
        "Player": "Brenton Thiels",
        "FIP": "5.10",
        "WHIP": "2.00",
        "K%": "7.69",
        "BB%": "7.69",
        "LOB%": "90.00"
    },
    {
        "Number": "45",
        "Player": "Jacob Havern",
        "FIP": "4.23",
        "WHIP": "1.50",
        "K%": "19.05",
        "BB%": "8.84",
        "LOB%": "80.49"
    },
    {
        "Number": "38",
        "Player": "Nate Crider",
        "FIP": "4.38",
        "WHIP": "1.37",
        "K%": "22.41",
        "BB%": "13.79",
        "LOB%": "79.17"
    },
    {
        "Number": "26",
        "Player": "Blake Hooks",
        "FIP": "4.78",
        "WHIP": "1.56",
        "K%": "19.35",
        "BB%": "10.92",
        "LOB%": "77.78"
    },
    {
        "Number": "36",
        "Player": "Greg Martinez",
        "FIP": "4.46",
        "WHIP": "1.58",
        "K%": "19.57",
        "BB%": "11.96",
        "LOB%": "81.43"
    },
    {
        "Number": "40",
        "Player": "Reed Smith",
        "FIP": "4.56",
        "WHIP": "1.42",
        "K%": "20.24",
        "BB%": "4.67",
        "LOB%": "77.68"
    },
    {
        "Number": "29",
        "Player": "Issac Crabb",
        "FIP": "4.47",
        "WHIP": "1.68",
        "K%": "21.62",
        "BB%": "16.22",
        "LOB%": "70.00"
    },
    {
        "Number": "28",
        "Player": "Caden Copeland",
        "FIP": "5.35",
        "WHIP": "1.75",
        "K%": "23.66",
        "BB%": "10.80",
        "LOB%": "72.22"
    },
    {
        "Number": "34",
        "Player": "Turner Swistak",
        "FIP": "4.94",
        "WHIP": "1.60",
        "K%": "18.35",
        "BB%": "5.66",
        "LOB%": "66.00"
    },
    {
        "Number": "39",
        "Player": "Ryan Harland",
        "FIP": "5.85",
        "WHIP": "1.73",
        "K%": "16.18",
        "BB%": "9.56",
        "LOB%": "71.05"
    },
    {
        "Number": "37",
        "Player": "Reece Tarini",
        "FIP": "5.67",
        "WHIP": "1.50",
        "K%": "9.09",
        "BB%": "9.09",
        "LOB%": "75.00"
    },
    {
        "Number": "46",
        "Player": "Hayden Harmon",
        "FIP": "-",
        "WHIP": "-",
        "K%": "-",
        "BB%": "-",
        "LOB%": "-"
    }
]

$(document).ready(function() {
    // Function to populate a table
    function populateTable(statsArray, tableId, fields) {
        const tbody = $('#' + tableId + ' tbody');
        tbody.empty(); // Clear existing rows

        statsArray.forEach(stat => {
            let row = $('<tr>');
            fields.forEach(field => {
                $('<td>').text(stat[field]).appendTo(row);
            });
            row.appendTo(tbody);
        });

        $('#' + tableId).tablesorter(); // Re-initialize tablesorter
    }

    // Define fields for each table
    const hittingFields = ["#", "Player", "AVG", "GP-GS", "AB", "R", "H", "2B", "3B", "HR", "RBI", "TB", "SLG%", "BB", "HBP", "SO", "GDP", "OB%", "SF", "SH", "SB-ATT"];
    const advHittingFields = ["Number","Player","OPS","SO%","BB%","RC","ISO","BABIP","wOBA"];
    const pitchingFields = ["#", "Player", "ERA", "W-L", "APP", "GS", "CG", "SHO", "SV", "IP", "H", "R", "ER", "BB", "SO", "2B", "3B", "HR", "B/AVG", "WP", "HP", "BK", "SFA", "SHA"];
    const advPitchingFields = ["Number","Player","FIP","WHIP","K%","BB%","LOB%"]
    const fieldingFields = ["#", "Player", "C","PO", "A", "E", "FLD%", "DP", "SBA", "CSB", "SBA%", "PB"];

    // Populate tables
    populateTable(HittingStats, 'hittingTable', hittingFields);
    populateTable(PitchingStats, 'pitchingTable', pitchingFields);
    populateTable(FieldingStats, 'fieldingTable', fieldingFields);
    populateTable(AdvBatting, 'advHittingTable', advHittingFields);
    populateTable(AdvPitching, 'advPitchingTable', advPitchingFields);

    $(document).ready(function() {
        $('#showHitting').click(function() {
            $('.tabcontent').hide(); // Hide all tabs
            $('#hittingStats').show(); // Show the hitting stats
        });
    
        $('#showPitching').click(function() {
            $('.tabcontent').hide(); // Hide all tabs
            $('#pitchingStats').show(); // Show the pitching stats
        });
    
        $('#showFielding').click(function() {
            $('.tabcontent').hide(); // Hide all tabs
            $('#fieldingStats').show(); // Show the fielding stats
        });
    
        $('#showAdvancedHitting').click(function() {
            $('.tabcontent').hide(); // Hide all tabs
            $('#advancedHittingStats').show(); // Show the advanced hitting stats
        });
    
        $('#showAdvancedPitching').click(function() {
            $('.tabcontent').hide(); // Hide all tabs
            $('#advancedPitchingStats').show(); // Show the advanced pitching stats
        });
    
        // Optionally, trigger the first tab to be open on page load
        $('#showHitting').trigger('click');
    });
    

    /* $(document).ready(function() {
        $(".tablesorter").tablesorter({
            theme: 'blue',
            widthFixed: true,
            widgets: ['zebra', 'filter']
        });
    
        // Event handlers for basic stats categories
        $('#showHitting').click(function() {
            $('#hittingStats').show();
            $('#pitchingStats').hide();
            $('#fieldingStats').hide();
            $('#advancedHittingStats').hide();
            $('#advancedPitchingStats').hide();
        });
    
        $('#showPitching').click(function() {
            $('#pitchingStats').show();
            $('#hittingStats').hide();
            $('#fieldingStats').hide();
            $('#advancedHittingStats').hide();
            $('#advancedPitchingStats').hide();
        });
    
        $('#showFielding').click(function() {
            $('#fieldingStats').show();
            $('#hittingStats').hide();
            $('#pitchingStats').hide();
            $('#advancedHittingStats').hide();
            $('#advancedPitchingStats').hide();
        });
    
        // Event handlers for advanced stats categories
        $('#showAdvancedHitting').click(function() {
            $('#advancedHittingStats').show();
            $('#hittingStats').hide();
            $('#pitchingStats').hide();
            $('#fieldingStats').hide();
            $('#advancedPitchingStats').hide();
        });
    
        $('#showAdvancedPitching').click(function() {
            $('#advancedPitchingStats').show();
            $('#hittingStats').hide();
            $('#pitchingStats').hide();
            $('#fieldingStats').hide();
            $('#advancedHittingStats').hide();
        });
    
        // Initially show basic hitting stats when the page loads
        $('#showHitting').trigger('click');
    }); */
    
    
});
